# Generated by Django 3.0.5 on 2020-05-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('pic', models.ImageField(upload_to='profile_pics')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('pic', models.ImageField(upload_to='profile_pics')),
                ('desc', models.TextField()),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.Domain')),
            ],
        ),
    ]
