# Generated by Django 3.0.5 on 2020-05-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
