# Generated by Django 3.0.5 on 2020-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_post_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='catagory',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
