# Generated by Django 3.0.5 on 2020-05-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20200514_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='This_blog_is_about',
            field=models.CharField(default=models.CharField(max_length=100), max_length=400),
        ),
    ]
