# Generated by Django 3.0.5 on 2020-05-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_post_this_blog_is_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='This_blog_is_about',
        ),
        migrations.AddField(
            model_name='post',
            name='is_about',
            field=models.CharField(default='This shows up in public blog! Choose well.', max_length=400),
        ),
    ]
